#==============================================================
#
#  Abs: Generate LCLS-II BCS IOCs Archive list  
#
#  Facility: LCLS-II Beam Containment System Controls
#
#  Auth: 06-Mar-2019, Kristi Luchini  (USERNAME)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        dd-mmm-yyyy, First Lastname  (USERNAME):
#          comment
#
#============================================================== 
#
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#

# Install archive list into $TOP/archive
ARCHIVE += sioc-gunb-rm01.archive
ARCHIVE += sioc-ltu0-rm01.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


