#==============================================================
#
#  Abs:  Makefile to build EPICS Database components
#
#  Name: Makefile
#
#  Facility: LCLS2
#
#  Auth: 21-Jul-2017, M. Dunning (MDUNNING)
#  Rev:  dd-mmm-yyyy, Reviewer's Name (USERNAME)
#--------------------------------------------------------------
#  Mod:
#       dd-mmm-yyyy, First Lastname    (USERNAME):
#         comment
#
#==============================================================

TOP=../..
include $(TOP)/configure/CONFIG
DIRS += common
DIRS += lcls
DIRS += site
DIRS += dev
include $(TOP)/configure/RULES_DIRS
