#==============================================================
#
#  Abs: Common Archive templates
#
#  Facility: EED Beam Containment System Controls
#
#  Auth: 06-Mar-2019, Kristi Luchini  (USERNAME)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        dd-mmm-yyyy, First Lastname  (USERNAME):
#          comment
#
#============================================================== 
#
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
ARCHIVE += $(IOCADMIN)/archive/archive_iocAdmin.archive

# Install archive list into $TOP/archive
ARCHIVE += dosfet.tpl-arch
ARCHIVE += dosfet-chan.tpl-arch
ARCHIVE += fht_6020.tpl-arch
ARCHIVE += monitor.tpl-arch
ARCHIVE += scan.tpl-arch

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


