#==============================================================
#
#  Abs: Common Archive templates
#
#  Facility: EED Radiation Monitoring Controls
#
#  Auth: 06-Mar-2019, Kristi Luchini  (LUCHINI)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        19-Oct-2021, K. Luchini      (LUCHINI):
#         chg facility
#
#============================================================== 
#
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
ARCHIVE += $(IOCADMIN)/archive/archive_iocAdmin.archive

# Install archive list into $TOP/archive
ARCHIVE += dosfet.tpl-arch
ARCHIVE += dosfet-chan.tpl-arch
ARCHIVE += fht_6020_common.tpl-arch
ARCHIVE += fht_6020_chan.tpl-arch
ARCHIVE += gamma6032.tpl-arch
ARCHIVE += hpi6012.tpl-arch
ARCHIVE += monitor.tpl-arch
ARCHIVE += scan.tpl-arch

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


