#==============================================================
#
#  Abs: Generate IOCs Archive list  
#
#  Facility: LCLS Radiation Monitoring Controls
#
#  Auth: 06-Mar-2019, Kristi Luchini  (LUCHINI):
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        19-Oct-2021, K. Luchini      (LUCHINI):
#          chg facility from bcs to radiation montitoring
#
#============================================================== 
#
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#

# Install archive list into $TOP/archive
ARCHIVE += sioc-undh-rm01.archive
ARCHIVE += sioc-unds-rm01.archive
ARCHIVE += sioc-bsy0-rm01.archive
ARCHIVE += sioc-bsyh-rm01.archive
ARCHIVE += sioc-gunb-rm01.archive
ARCHIVE += sioc-ltu0-rm01.archive
ARCHIVE += sioc-clts-rm01.archive
ARCHIVE += sioc-und0-rm01.archive
ARCHIVE += sioc-und0-rm02.archive
ARCHIVE += sioc-sysw-rm01.archive
ARCHIVE += sioc-sys0-rm01.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


