#==============================================================
#
#  Abs: Generate LCLS BCS IOCs Archive list  
#
#  Facility: LCLS Beam Containment System Controls
#
#  Auth: 06-Mar-2019, Kristi Luchini  (USERNAME)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        dd-mmm-yyyy, First Lastname  (USERNAME):
#          comment
#
#============================================================== 
#
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#

# Install archive list into $TOP/archive
#ARCHIVE += ioc-in20-bc01.archive
#ARCHIVE += ioc-li24-bc01.archive
#ARCHIVE += ioc-li28-bc01.archive
#ARCHIVE += ioc-ltu1-bc01.archive
#ARCHIVE += ioc-ltu1-bc02.archive
#ARCHIVE += ioc-dmp1-bc01.archive
#ARCHIVE += ioc-mcc0-bc01.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


