#==============================================================
#
#  Abs: Generate IOCs Archive list  
#
#  Facility: FACET Radiatin Monitor Controls
#
#  Auth: 19-Oct-2021, Kristi Luchini  (USERNAME)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        dd-mmm-yyyy, First Lastname  (USERNAME):
#          comment
#
#============================================================== 
#
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
# Install archive list into $TOP/archive
ARCHIVE += sioc-li20-rm01.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


